# Generated by Django 5.0.6 on 2024-06-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_deliveryschedules_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryvehicle',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryvehicle',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
