# Generated by Django 5.0.6 on 2024-06-04 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_deliveryvehicle_expiration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryvehicle',
            name='expiration_date',
        ),
    ]
