# Generated by Django 5.0.6 on 2024-06-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_deliveryvehicle_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryvehicle',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
